//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2_ds411.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transacciones
    {
        public int cod_transac { get; set; }
        public Nullable<double> monto { get; set; }
        public string tipo { get; set; }
        public Nullable<int> ncta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual cuenta cuenta { get; set; }
    }
}
